# -*- coding: utf-8 -*-
"""Aritificial_Neural_Network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFbO8etqJmvtfurACtP47PEPz5o95LsF
"""

!pip install Cython
!pip install https://github.com/Santosh-Gupta/scikit-learn/archive/master.zip

import pandas as pd
import numpy as np
import tensorflow as tf

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1]
y = dataset.iloc[:, -1]

# Encoding "Gender"
le = LabelEncoder()
x.iloc[:, 2] = le.fit_transform(x.iloc[:, 2])

# Enconding "Geography"
x.iloc[:, 1] = le.fit_transform(x[["Geography"]])# As a result, we have: France = 0; Germay = 1; Spain = 2
x

# Define training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Feature scaling
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Create our aritificial neural network
ann = tf.keras.models.Sequential()

# Add input layer and first hidden layer to ANN
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Add second layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Add the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))