# -*- coding: utf-8 -*-
"""Aritificial_Neural_Network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFbO8etqJmvtfurACtP47PEPz5o95LsF
"""

import pandas as pd
import numpy as np
import tensorflow as tf

dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1]
y = dataset.iloc[:, -1]